const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
const BLE=require('./ble_images.js'),Codec=require('./photo_codec.js');
function mock({failAt=0,stale=false,error=false}={}){
 let status='IMG1:READY',received=0,clock=0,id='',writes=[],active=false;const buffer=new Uint8Array(BLE.SIZE);
 const io={read:async()=>{assert.equal(active,false);return status;},write:async a=>{assert.equal(active,false);active=true;try{writes.push(a.slice());assert.ok(a.length<=20);if(writes.length===failAt)throw Error('Disconnected');const v=new DataView(a.buffer,a.byteOffset,a.byteLength);id=v.getUint32(1,true).toString(16).padStart(8,'0');if(a[0]===1){received=0;assert.equal(v.getUint16(5,true),296);assert.equal(v.getUint16(7,true),128);assert.equal(v.getUint16(10,true),9472);status=`RECV:${id}:0`;}if(a[0]===2){assert.equal(v.getUint16(5,true),received);buffer.set(a.subarray(7),received);received+=a.length-7;status=`RECV:${id}:${received}`;}if(a[0]===3){assert.equal(received,9472);status=error?`ERR:${id}:CRC`:stale?'DONE:deadbeef:100':`REFRESH:${id}`;}}finally{active=false;}}};
 const env={now:()=>clock,sleep:async ms=>{clock+=ms;if(status===`REFRESH:${id}`)status=`DONE:${id}:12345`;}};
 return{io,env,buffer,writes,get status(){return status;},set status(s){status=s;}};
}
test('two distinct images round-trip in bounded frames; completion and timing are separate',async()=>{const m=mock();for(const [id,value] of [[1,0x55],[2,0xaa]]){const bytes=new Uint8Array(9472).fill(value),events=[];const result=await BLE.send(m.io,bytes,3,id,p=>events.push(p),m.env);assert.deepEqual(m.buffer,bytes);assert.equal(result.panelMs,12345);assert.equal(events.at(-1).stage,'refreshing');assert.equal(events.at(-1).bytes,9472);}});
test('previous transfer error cannot reject new transfer before fresh status is published',async()=>{const m=mock();const read=m.io.read;let stale=true;m.io.read=async()=>{if(m.writes.length===1&&stale){stale=false;return 'ERR:deadbeef:CRC';}return read();};const result=await BLE.send(m.io,new Uint8Array(9472),2,1,()=>{},m.env);assert.equal(result.id,1);});
test('old text firmware refused before any write',async()=>{const m=mock();m.status='FINISHED';await assert.rejects(BLE.send(m.io,new Uint8Array(9472),2,1,()=>{},m.env),/firmware/);assert.equal(m.writes.length,0);});
test('active image receiver refused before write',async()=>{const m=mock();m.status='RECV:00000009:13';await assert.rejects(BLE.send(m.io,new Uint8Array(9472),2,1,()=>{},m.env),/busy/);assert.equal(m.writes.length,0);});
test('write failure is not retried or committed',async()=>{const m=mock({failAt:5});await assert.rejects(BLE.send(m.io,new Uint8Array(9472),2,1,()=>{},m.env),/Disconnected/);assert.equal(m.writes.length,5);assert.ok(m.writes.every(a=>a[0]!==3));});
test('stale completion with wrong transfer id cannot satisfy this transfer',async()=>{const m=mock({stale:true});await assert.rejects(BLE.send(m.io,new Uint8Array(9472),2,1,()=>{},m.env),/timed out/);});
test('checksum rejection is surfaced, never completion',async()=>{const m=mock({error:true});await assert.rejects(BLE.send(m.io,new Uint8Array(9472),2,1,()=>{},m.env),/CRC/);});
test('palette and length invalidity rejected before transport',()=>{assert.throws(()=>BLE.begin(1,new Uint8Array(4),2));assert.throws(()=>BLE.begin(1,new Uint8Array(9472).fill(0xff),3));assert.throws(()=>BLE.begin(1,new Uint8Array(9472).fill(0xaa),2));});
test('copied photo codec round trips palette bytes and CRC agrees with binary sender',()=>{const codes=Uint8Array.from({length:296*128},(_,i)=>i%3);const text=Codec.encode(codes);assert.deepEqual(Codec.decode(text),codes);const bytes=Uint8Array.from(text.slice(22).match(/../g),s=>parseInt(s,16));assert.equal(BLE.crc32(bytes),parseInt(text.slice(13,21),16));assert.equal(Codec.preview(codes).length,296*128*4);});
test('file checks reject HEIC, empty, oversized input; accept JPEG and PNG',()=>{assert.throws(()=>Codec.checkFile(1,[0,0,0]));assert.throws(()=>Codec.checkFile(0,[255,216,255]));assert.throws(()=>Codec.checkFile(11*1024*1024,[255,216,255]));Codec.checkFile(3,[255,216,255]);Codec.checkFile(8,[137,80,78,71,13,10,26,10]);});
function ui({supported=true,status='IMG1:READY'}={}){
 const ids=['connect','read','send','disconnect','status','log','editor','photo','palette','cropX','cropY','zoom','cropCanvas','preview','message','progress','mode','text','textColor','textControls','photoControls'];
 const nodes=Object.fromEntries(ids.map(id=>[id,{disabled:false,textContent:'',value:id==='zoom'?'1':'50',files:[],addEventListener(e,f){this[e]=f;},getContext(){return{clearRect(){}};}}]));
 const device={addEventListener(e,f){this[e]=f;},gatt:{connected:false,async connect(){this.connected=true;return{getPrimaryService:async()=>({getCharacteristic:async()=>({readValue:async()=>new TextEncoder().encode(status)})})};},disconnect(){this.connected=false;device.gattserverdisconnected();}}};
 const ctx={document:{getElementById:id=>nodes[id]},window:{isSecureContext:true},navigator:{bluetooth:supported?{requestDevice:async()=>device}:undefined},TextEncoder,TextDecoder,setTimeout,clearTimeout,BLEImages:BLE,PhotoCodec:Codec};vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/app.js','utf8'),ctx);return{nodes,device,ctx};
}
test('unsupported browser has usable guidance and cannot connect',()=>{const s=ui({supported:false});assert.equal(s.nodes.connect.disabled,true);assert.match(s.nodes.status.textContent,/Bluefy/);});
test('connect and disconnect work, no photo means no send',async()=>{const s=ui();await s.nodes.connect.click();assert.equal(s.nodes.read.disabled,false);assert.equal(s.nodes.send.disabled,true);s.nodes.disconnect.click();assert.equal(s.nodes.read.disabled,true);});
test('old firmware connect displays error and disconnects',async()=>{const s=ui({status:'FINISHED'});await s.nodes.connect.click();assert.equal(s.device.gatt.connected,false);assert.match(s.nodes.status.textContent,/new epaper_ble_images/);});
test('new selection invalidates previously prepared payload immediately',async()=>{const s=ui();vm.runInContext('prepared={bytes:new Uint8Array(9472),palette:2}',s.ctx);await s.nodes.photo.change();assert.equal(vm.runInContext('prepared',s.ctx),null);assert.equal(s.nodes.send.disabled,true);});
